[2023-11-02T21:04:51.433+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Google_Job_Listings_Data_Pipeline.feature_engineering manual__2023-11-02T20:58:42.985422+00:00 [queued]>
[2023-11-02T21:04:51.447+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Google_Job_Listings_Data_Pipeline.feature_engineering manual__2023-11-02T20:58:42.985422+00:00 [queued]>
[2023-11-02T21:04:51.447+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2023-11-02T21:04:51.466+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): feature_engineering> on 2023-11-02 20:58:42.985422+00:00
[2023-11-02T21:04:51.473+0000] {standard_task_runner.py:57} INFO - Started process 644 to run task
[2023-11-02T21:04:51.478+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Google_Job_Listings_Data_Pipeline', 'feature_engineering', 'manual__2023-11-02T20:58:42.985422+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/extract_job_data_dag.py', '--cfg-path', '/tmp/tmpy4sqqbg2']
[2023-11-02T21:04:51.480+0000] {standard_task_runner.py:85} INFO - Job 61: Subtask feature_engineering
[2023-11-02T21:04:51.546+0000] {task_command.py:410} INFO - Running <TaskInstance: Google_Job_Listings_Data_Pipeline.feature_engineering manual__2023-11-02T20:58:42.985422+00:00 [running]> on host 1f525f761703
[2023-11-02T21:04:51.640+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Google_Job_Listings_Data_Pipeline' AIRFLOW_CTX_TASK_ID='feature_engineering' AIRFLOW_CTX_EXECUTION_DATE='2023-11-02T20:58:42.985422+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-02T20:58:42.985422+00:00'
[2023-11-02T21:04:51.642+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-02T21:04:51.643+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/extraction/feature_engineering.py 20231102']
[2023-11-02T21:04:51.658+0000] {subprocess.py:86} INFO - Output:
[2023-11-02T21:04:52.888+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-11-02T21:04:52.889+0000] {subprocess.py:93} INFO -   File "/opt/***/extraction/feature_engineering.py", line 18, in <module>
[2023-11-02T21:04:52.890+0000] {subprocess.py:93} INFO -     with open('./tools.txt', 'r') as file:
[2023-11-02T21:04:52.890+0000] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: './tools.txt'
[2023-11-02T21:04:53.048+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-11-02T21:04:53.070+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-11-02T21:04:53.075+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=Google_Job_Listings_Data_Pipeline, task_id=feature_engineering, execution_date=20231102T205842, start_date=20231102T210451, end_date=20231102T210453
[2023-11-02T21:04:53.097+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 61 for task feature_engineering (Bash command failed. The command returned a non-zero exit code 1.; 644)
[2023-11-02T21:04:53.134+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-11-02T21:04:53.161+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
